---
  - hosts: localhost
    gather_facts: false
    become: yes
    tasks:
      - yum:
         name: git
         state: present
      - yum:
         name: wget
         state: present
      - yum:
         name: pip3
         state: present
      - yum:
         name: tree
         state: present
      - yum:
         name: vim
         state: present
